{% set name = "flask-swagger" %}
{% set version = "0.2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4085f5bc36df4c20b6548cd1413adc9cf35719b0f0695367cd542065145294d

build:
  noarch: python
  number: 3
  script: {{PYTHON}} -m pip install --no-deps --no-build-isolation --ignore-installed . -vv

  entry_points:
    - flaskswagger=build_swagger_spec:run

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - flask >=0.10
    - pyyaml >=5.1

test:
  imports:
    - flask_swagger
  requires:
    - pip
  commands:
    - pip check
    - flaskswagger --help

about:
  home: https://github.com/getsling/flask-swagger
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Extract swagger specs from your flask project
  description: Extract swagger specs from your flask project
  dev_url: https://github.com/getsling/flask-swagger
  doc_url: https://github.com/getsling/flask-swagger

extra:
  recipe-maintainers:
    - sodre
    - xylar
