{% set name = "flask-swagger" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42420efbed1aad86f7ca6bb869df550e09591e1d540ebd3040c197906c0f0be6

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

  entry_points:
    - flaskswagger=build_swagger_spec:run

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - flask >=0.10
    - pyyaml >=5.1

test:
  commands:
    - flaskswagger --help

  imports:
    - flask_swagger

about:
  home: http://github.com/gangverk/flask-swagger
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Extract swagger specs from your flask project'

  dev_url: https://github.com/gangverk/flask-swagger

extra:
  recipe-maintainers:
    - sodre
    - xylar
