travis:
  secure:
    BINSTAR_TOKEN: MW7rg4L57f8ZOPKUJOAuLmRpPMpsCHmxkATiNH4nokUiRJA+6OhesYP4nHioLz0/ikuiiwF9fQiQH/REb8iNaFEDS1IOCcGFj1MuXu0d3ol+Tt6wc5emseriyCHmOpBgCcqdpz75SviHOJNH3ZXA4hCI3YofcLaT1CisDUvkWoIj394Wm9sbvi557EdYwmhteJ2R4CiorpjCqyyiHhryIe3+6gVSmJXPvFyR5m8UVSaGEU5oM2Dw7SZx/0jCzNxgL0/SgkLyXZoMq7gzmjQ6Zsege4GySW1QjvSbVyqzmnopRRGM38NlJORViNXLRtq4FXfpXGoevNQ9apo9DbHYAxk636+NEjNz+AXnXaeecHIT0qT3iJz4FByDvcXhikyhFm/zQHCQ7eeHg8St6AWn4TUsvcBzYkCjrNkrXr8MI0XdS4EbcFG/vU+VhZVY+LYnF3HpOzYzKSnWUzcv5LugA0EbGI0mqZCSX+31X+ph5cVXT4jTHh4btzz+qshhHdwP6bn0FIFgASe+HvTGdDtj/cn+I+kTNDEoCAtHKlQBFSLNxYpEtu1yPcJMtosb16KTmyTqaqrVLxjVvtfcz8W/0J1b/FTs730lv0f5l+aNSi6FnnCeNR/dnnGAfA6JDaxLfYtgjERlQu9BOoLiSbwzX67iGOGL7EEi+XjtkNEii4o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
