travis:
  secure:
    BINSTAR_TOKEN: kH8s1R0sR6VgGBjRdjl5y5rLT/6A6QVG4ew8c7R5ji1obLcaQtLQJ+kqGXFmCch6SqSbO+0yswXqZ74uvTYwwrBa1K4VNxqQCH12hP0bz+embZV6Idp2jI03GZy7aIF5HZbaaDJll9g+GKQnATqqQw9i6TKPpcAyfk5+EmLwpzOGXsavkYWMWR4iFgSyx6oWAUsWB9A6QdpPqq9Lrf7w8MFad2P4QZcakYmEnNL5Qw78TKJ8oxBD5aY1Ykxxn8NeKWabuAUZu0Ih/z8MQlYqI4MJbQ6UVMY50cYP5vIjaLK6qBckCmmyLfOGjaMUVTWSY/bfBPDW4tAfR67h4JLrwRaTlHFx8USCifDs5fS+gR2cBpoc6bMnBVCoyZtrwzHUx6oH293xUl9Yo+HXG8HcseMJHNp/WwHNHsNBPKu2MLSSbE4+uSQaxXmXyXGTWPDmdZpJwRvV/5O7u8avpTBA/31uvhhov6I0ZAwapSxRH07XSMpjx69uBm102yafeOmAb0UqX/9y8Qsqokr7uqxFJlGO9Vc7VeMWdvEaMWo4PonrS+OrJKS7vPFFC1zgmeEfpRVJcadto2yWlepwxxZCXuLIiyl2ISSFCIerAP6BJqLmchjMYSINCmxtp7GJLLJdPa19nSN3ebjgO3oQjL2exJL22zgDk0Dfk8buAQRDSTg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
